### ISSUE TITLE
Filtered downloads are empty

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#107]
Steps to reproduce

1. Navigate to events https://events.test.ala.org.au/ 
2. Click on 'Events' tab
3. Apply some filters and make sure the number of events changes accordingly
4. Click 'Download' tab
5. Click the 'Download' button, and then click 'Download filtered dataset' button and follow any additional prompts
6. Wait for the email to arrive

Expected

- Archive accessible via email should contain a non empty events.txt file

Actual 

- The events.txt and occurrences.txt files are empty.

This is the query used https://events.test.ala.org.au/?datasetKey=dr359&samplingProtocol=incidental%20search&state=fbb0bc657366467eba51cbed2ba12a3e&view=SURVEYS

**Comment by djtfmartin** [comment]
Thanks @javier-molina - can you provide the exact query you used ?

**Comment by djtfmartin** [comment]
this is fixed in the test environment. The issue was specific to the samplingProtocol filter.
 
 Fix was in this commit: https://github.com/gbif/gbif-web/commit/9c03591a39d8efd7e0e41902dd72dcfff90e0681
