### ISSUE TITLE
Add event fields to facets

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#17]
Event fields need to be added to facets on biocache hubs

ParentEventId and field number are fields available in the index but not in the UI 

![Screen Shot 2022-02-08 at 2 48 40 pm](https://user-images.githubusercontent.com/8326394/152914586-239f9c23-d60b-414b-936d-f1b87ca3e9f2.png)

**Comment by adam-collins** [comment]
Plan to ensure that these facets are available: eventID, parentEventID, fieldNumber, samplingProtocol.

**Comment by adam-collins** [comment]
Settled on adding `parentEventID`, `fieldNumber`, `datasetName`. `eventID` exists already.

Changes available in the `customise filters` list under the `Occurrences` section of https://biocache-databox.ala.org.au

**Comment by qifeng-bai** [comment]
Requirement changed. The new requirement is in #29
