### ISSUE TITLE
Validate archive content

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#58]
Archives downloaded from event system contain separate files with events, occurrences and measurement and facts with metadata files for both Darwin Core Archives and frictionless.

Is there anything substantially missing in the information and the format it is delivered?

Test filtered and full datasets

Access is here

https://events-test.ala.org.au/?view=DOWNLOAD

**Comment by charvolant** [comment]
Add EML file

**Comment by javier-molina** [comment]
Feedback from Shandiya


> 1. The following fields were not included in verbatim_event.txt: samplingEffort, eventRemarks, organismQuantity, organismQuantityType, and occurrenceStatus. I think it would be very useful to add them, if possible.
> 2. Reviewing occurrences taxonomically was a bit difficult because taxonomic ranks in verbatim_occurrence.txt (phylum, class, order, family, scientificName) were not ordered. It would be very helpful to order the columns in this way.
> 3. I expected that the output would contain every occurrence record associated with an event, but it didn’t look like that was the case (maybe I misunderstood?). I got around this by joining verbatim_event.txt and verbatim_occurrence.txt, but it would be much more helpful if the data were output this way to begin with. I’d be happy to discuss this further if I’ve misunderstood the outputs currently generated.

**Comment by djtfmartin** [comment]
Responding to Shandiya
1. this is expected. The `verbatim_event.txt` file only contains the fields that where originally supplied in the DwCA from the data publisher
2. the same is true for the `verbatim_occurrence.txt`. It only contains the fields that where originally supplied in the DwCA from the data publisher
3. Yes,  the output *should* contain every occurrence record associated with an event. We need an example query to test this.

**Comment by javier-molina** [comment]
@shandiya see responses to your comments above.

Would you be able to share a query to reproduce the issue from point 3?

**Comment by shandiya** [comment]
@djtfmartin I think point 3 was poorly phrased on my part. The output does contain every occurrence record associated with an event, but I assumed occurrences and events would have been provided in the one file, with a more hierarchical structure, rather than multiple files with a relational structure. It was a bit tricky to understand what the different field names referred to, as there were multiple columns relating to id. 

I did notice something else while looking at this again, but I'm not sure if it's under your control or something that would have to be done by the data provider. It would be nice to be able to order the id columns (id, eventID, parentEventID) while looking at the data, but this isn't currently possible because the end numbers are not left-padded (e.g. 10000001-0-100 comes before 10000001-0-11). Very much a nice-to-have, not something that actually affects the data.

**Comment by djtfmartin** [comment]
Thanks @shandiya. Could you elaborate on what a hierarchical structure might look like ? 
We should explore other formats. Im not convinced providing DwCAs is very helpful to end users.

**Comment by shandiya** [comment]
I was envisioning something that looks like this (maybe hierarchical is not the right word?):

| eventID  | occID | date | samplingProtocol | count | kingdom | phylum | ... | species | lat | lon |
| ---- | ------ | ------------- | -------------  |------ | ------ |-------- | -------  | ----- | --- | --- |
| 001  | 01  | 2010-10-14 | mist-net  | 3  | Animalia  | Chordata  | ...  | Pardalotus punctatus | -37.1 | 144.2 |
| 001  | 02 | 2010-10-14  | mist-net  | 4 | Animalia  | Chordata  | ...  | Pardalotus striatus | -37.1 | 144.2 |
| 001  | 03  | 2010-10-14  | mist-net  | 8 | Animalia  | Chordata  | ...  | Pardalotus rubricatus | -37.1 | 144.2 |
| 002  | 01 | 2010-11-28 | 2 ha 20 min | 2 | Animalia  | Chordata  | ...  | Colluricincla harmonica | -37.2 | 144.5 |
| 002  | 02  | 2010-11-28  | 2 ha 20 min | 1 | Animalia  | Chordata  | ...  | Chenonetta jubata | -37.2 | 144.5 |
| 002  | 03 | 2010-11-28  | 2 ha 20 min  | 2 | Animalia  | Chordata  | ...  | Coracina novaehollandiae | -37.2 | 144.5 |

These are dummy values, but I was imagining something where summed counts of a species, detected using a given sampling protocol, during a particular event, would make up what I've been referring to as occurrences (here occID). I thought it would be useful to be able to see this all in the one table, where occurrences for every event are listed together with information on the event, even though it would result in a lot of duplicated information. Is size of data downloads an issue?

**Comment by djtfmartin** [comment]
thanks @shandiya - this is useful and worth exploring.
I think what we are talking about here is some sort of aggregated view of the data.
It may actually be worth supporting several exports formats for different use cases.

The above looks to me just like occurrences + eventIDs - which is what the biocache already supports.

**Comment by javier-molina** [comment]
No concrete new format was identified after meeting with @shandiya on 19 Jan. We will revisit this in the future.
