### ISSUE TITLE
Include quality assertions in downloads

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#61]
Currently occurrence quality assertions are not included in the download archive. 
Assertions should go in the occurrences.csv, as they are in current downloads, with the definition url going in the meta.xml and datapackage.json

**Comment by javier-molina** [comment]
@peggynewman and @charvolant to work on this design.

**Comment by peggynewman** [comment]
The assertions should go in the occurrences.csv, as they are in current downloads, with the definition url going in the meta.xml

**Comment by javier-molina** [comment]
@javier-molina to test.

**Comment by javier-molina** [comment]
Tested successfully for filtered and full dataset.

issue field contains assertions in occurrence.txt

datapackage.json and meta.xml contain issue definition accordingly
