### ISSUE TITLE
Use Leaflet-like base layer for maps 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#76]
The current layer for the map view is orange and black, which deviates from the layer from other products such as BIE and Biocache.

Switch layer to leaflet base layer or a layer that is close to it.

**Comment by qifeng-bai** [comment]
https://github.com/gbif/gbif-web/commit/c999f78980909db37dd944b20d5e1a40f0bf9276

This commit contains other changes.

**Comment by javier-molina** [comment]
As discussed previously, the contrast needs to be increased to make it easier to see points on the map.

![Image](https://user-images.githubusercontent.com/8326394/212218737-9ea43afa-8a47-4369-b62a-8c176510318a.png)

**Comment by qifeng-bai** [comment]
Style changed on getLayerConfig.js

in this commit : https://github.com/gbif/gbif-web/commit/719514620329b48a237edb6021831882b34dff08

**Comment by qifeng-bai** [comment]
PR: https://github.com/gbif/gbif-web/pull/298

PR approved and merged
