### ISSUE TITLE
Add breadcrumb link

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#77]
Add breadcrumb link

The link should take you back to event system homepage with all filters cleared.

[Event System UX-UI.docx](https://csiroau.sharepoint.com/:w:/r/sites/ALA/Shared%20Documents/General/Implementation/Event%20System%20UX-UI.docx?d=wcb7865bd1dfb42d09e77e8313cb11129&csf=1&web=1&e=SEKehT)

**Comment by qifeng-bai** [comment]
Add a 'reset' button at the right of filter bar.

Not be able to add reset function to the 'home link', since this part is out of ReactJS scope.

![Screen Shot 2022-11-02 at 4 17 30 pm](https://user-images.githubusercontent.com/31238531/199404250-724230e8-18b7-4e9a-b9d5-812acb56dca9.png)

**Comment by javier-molina** [comment]
Covered by reset filters button in #68
