### ISSUE TITLE
Deploy node components

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#80]
Dockerise Node.js components

**Comment by javier-molina** [comment]
Related comment from Nick:

Use AWS Amplify and apollo to produce a CD/CI pipeline to deploy components.

**Comment by djtfmartin** [comment]
PR awaiting review: https://github.com/AtlasOfLivingAustralia/ala-install/pull/635

**Comment by javier-molina** [comment]
Bai tested this several times
