### ISSUE TITLE
Occurrences not queryable by eventID

### ISSUE THREAD

**Issue by jack-brinkman** [AtlasOfLivingAustralia/extended-data-model#84]
Currently, occurrences cannot be queried by `eventID`, only `eventHierarcy`, which returns irrelevant results for some use cases (i.e. querying occurrences directly related to an event, see gbif/gbif-web#217).

### Example URL
[https://events-test.ala.org.au/es/occurrence?apiKey=my-api-key&body={"eventID":"c4d99bf5-9653-43d9-923a-0780da3e47f6"}](https://aws-events-es-2022.ala.org.au/es/event-occurrence?apiKey=my-api-key&eventId=1137323)

### Event Information
We can see that this event (c4d99bf5-9653-43d9-923a-0780da3e47f6) has one related occurrence - the `/occurrence` endpoint is returning none.

![image](https://user-images.githubusercontent.com/104949733/204171940-705396d0-c33f-40c8-a68d-4885687ecf10.png)

**Comment by jack-brinkman** [comment]
As `eventHierarchy` still returns all the required occurrences, I'm happy to just filter out the ones that aren't directly related to the event for the time being.

EDIT: @MortenHofft has kindly fixed this issue :)

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/gbif-web/issues/223
